In [15]:

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import  LinearRegression
from sklearn.metrics import accuracy_score , classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve
from sklearn.preprocessing import StandardScaler
import gradio as gr

c:\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
wine_ds=pd.read_csv("redAndWhite.csv")
print(wine_ds.shape)
wine_ds.isnull().sum()
wine_ds.describe

(6497, 13)


<bound method NDFrame.describe of        type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  tot

In [3]:
#data analysis and visualization
#statistical of dataset
wine_ds.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378  
std       0.160787     0.148806     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [4]:
wine_ds.tail()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
6492  red            6.2             0.600         0.08             2.0   
6493  red            5.9             0.550         0.10             2.2   
6494  red            6.3             0.510         0.13             2.3   
6495  red            5.9             0.645         0.12             2.0   
6496  red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
6492       0.58     10.5        5  
6493       0.76     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6

In [5]:
wine_ds['type'] = wine_ds['type'].map({'red': 0, 'white': 1})

In [6]:
wine_ds.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     1            7.0              0.27         0.36            20.7   
1     1            6.3              0.30         0.34             1.6   
2     1            8.1              0.28         0.40             6.9   
3     1            7.2              0.23         0.32             8.5   
4     1            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [7]:
# get data with wine quality greater than 4 and less than 8
#wine_ds = wine_ds[(wine_ds['quality'] > 4) & (wine_ds['quality'] < 8)]

# reset index and drop the old one
wine_dss = wine_ds  
#.reset_index(drop=True)

wine_dss.to_csv('data.csv', index=False)

In [8]:
X=wine_dss.drop('quality',axis=1)
Y=wine_dss['quality']
Y.to_csv('data.csv', index=False)
#train test  split
X_train , X_test , Y_train ,Y_test= train_test_split(X , Y , test_size=0.2 , random_state=2)

In [9]:
print(Y.shape , Y_train.shape, Y_test.shape)

(6497,) (5197,) (1300,)


In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
model=RandomForestClassifier()
model.fit(X_train,Y_train)

RandomForestClassifier()

In [12]:
X_test_preedection=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_preedection,Y_test)
print('accuracy :', test_data_accuracy)

accuracy : 0.6953846153846154


In [18]:
def predict_wine_quality_array(input_array):
    # Convert the comma-separated string to a list of numbers
    input_values = [float(val) for val in input_array.split(',')] 
    input_data_reshape = np.array(input_values).reshape(1, -1)
    prediction = model.predict(input_data_reshape)
    if prediction[0] == 0:
        pred = 'wine quality is bad'
    else:
        pred = 'wine quality is good'
    return pred

def predict_wine_quality_individual(type, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
                                     free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol):
    # Convert the 'type' input to an integer (0 for Red, 1 for White)
    if type == 'Red':
        type = 0
    else:
        type = 1

    input_data = (type, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
                  free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol)
    input_data_as_nparray = np.asarray(input_data)
    input_data_reshape = input_data_as_nparray.reshape(1, -1)

    prediction = model.predict(input_data_reshape)
    if prediction[0] == 0:
        pred = 'wine quality is bad'
    else:
        pred = 'wine quality is good'
    return pred , prediction[0]

# Mean values
mean_values = [6.9, 0.21, 0.33, 1.8, 0.034, 48, 136, 0.9899, 3.25, 0.41, 12.6]

# Create Gradio interface
with gr.Blocks() as demo:
    gr.Markdown("## Wine Quality Predictor")
    gr.Markdown("Select input method:")

    with gr.Row():
        button_array = gr.Button("Input Array")
        button_individual = gr.Button("Individual Input")

    with gr.Row():
        input_array = gr.Textbox(label="Enter values as comma-separated list (e.g., 0,7,0.2,0.3,...)",
                                 value=",".join(str(val) for val in mean_values))
        
        type_radio = gr.Radio(['Red', 'White'], label="Type")
        fixed_acidity = gr.Number(label="Fixed Acidity", value=mean_values[0])
        volatile_acidity = gr.Number(label="Volatile Acidity", value=mean_values[1])
        citric_acid = gr.Number(label="Citric Acid", value=mean_values[2])
        residual_sugar = gr.Number(label="Residual Sugar", value=mean_values[3])
        chlorides = gr.Number(label="Chlorides", value=mean_values[4])
        free_sulfur_dioxide = gr.Number(label="Free Sulfur Dioxide", value=mean_values[5])
        total_sulfur_dioxide = gr.Number(label="Total Sulfur Dioxide", value=mean_values[6])
        density = gr.Number(label="Density", value=mean_values[7])
        pH = gr.Number(label="pH", value=mean_values[8])
        sulphates = gr.Number(label="Sulphates", value=mean_values[9])
        alcohol = gr.Number(label="Alcohol", value=mean_values[10])

    output = [gr.Textbox(label="Prediction"),prediction]

    # Connect buttons to functions
    button_array.click(fn=predict_wine_quality_array, inputs=input_array, outputs=output)

    button_individual.click(fn=predict_wine_quality_individual,
                          inputs=[type_radio, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
                                 free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol],
                          outputs=output)

    # Correct visibility toggle using .change events
    def show_array_input():
        input_array.visible = True
        type_radio.visible = False
        fixed_acidity.visible = False
        volatile_acidity.visible = False
        citric_acid.visible = False
        residual_sugar.visible = False
        chlorides.visible = False
        free_sulfur_dioxide.visible = False
        total_sulfur_dioxide.visible = False
        density.visible = False
        pH.visible = False
        sulphates.visible = False
        alcohol.visible = False
        return input_array, type_radio, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, \
               free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol

    def show_individual_input():
        input_array.visible = False
        type_radio.visible = True
        fixed_acidity.visible = True
        volatile_acidity.visible = True
        citric_acid.visible = True
        residual_sugar.visible = True
        chlorides.visible = True
        free_sulfur_dioxide.visible = True
        total_sulfur_dioxide.visible = True
        density.visible = True
        pH.visible = True
        sulphates.visible = True
        alcohol.visible = True
        prediction.visible= True
        return input_array, type_radio, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, \
               free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol,

    # **Correctly connecting button clicks to visibility functions**
    button_array.click(
        fn=show_array_input,
        inputs=[],
        outputs=[input_array, type_radio, fixed_acidity, volatile_acidity, citric_acid,
                 residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide,
                 density, pH, sulphates, alcohol,]
    )

    button_individual.click(
        fn=show_individual_input,
        inputs=[],
        outputs=[input_array, type_radio, fixed_acidity, volatile_acidity, citric_acid,
                 residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide,
                 density, pH, sulphates, alcohol,]
    )

demo.launch()

NameError: name 'prediction' is not defined

In [16]:
def predict_wine_quality_array(input_array):
    # Convert the comma-separated string to a list of numbers
    input_values = [float(val) for val in input_array.split(',')] 
    input_data_reshape = np.array(input_values).reshape(1, -1)
    prediction = model.predict(input_data_reshape)
    if prediction[0] == 0:
        pred = 'wine quality is bad'
    else:
        pred = 'wine quality is good'
    return pred

def predict_wine_quality_individual(type, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
                                     free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol):
    # Convert the 'type' input to an integer (0 for Red, 1 for White)
    if type == 'Red':
        type = 0
    else:
        type = 1

    input_data = (type, fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
                  free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol)
    input_data_as_nparray = np.asarray(input_data)
    input_data_reshape = input_data_as_nparray.reshape(1, -1)

    prediction = model.predict(input_data_reshape)
    if prediction[0] == 0:
        pred = 'wine quality is bad'
    else:
        pred = 'wine quality is good'
    return pred

# Mean values
mean_values = [6.9, 0.21, 0.33, 1.8, 0.034, 48, 136, 0.9899, 3.25, 0.41, 12.6]

# Create Gradio interface
with gr.Blocks() as demo:
    gr.Markdown("## Wine Quality Predictor")
    gr.Markdown("Select input method:")

    with gr.Row():
        button_array = gr.Button("Input Array")
        button_individual = gr.Button("Individual Input")

    # Create a container for the inputs
    with gr.Row(visible=True) as input_container:  # Make container visible by default
        input_array_textbox = gr.Textbox(label="Enter values as comma-separated list (e.g., 0,7,0.2,0.3,...)",
                                 value=",".join(str(val) for val in mean_values))

        # Individual inputs (visible by default)
        with gr.Group(visible=True) as individual_inputs:  # Make group visible by default
            type_radio_individual = gr.Radio(['Red', 'White'], label="Type")
            fixed_acidity_individual = gr.Number(label="Fixed Acidity", value=mean_values[0])
            volatile_acidity_individual = gr.Number(label="Volatile Acidity", value=mean_values[1])
            citric_acid_individual = gr.Number(label="Citric Acid", value=mean_values[2])
            residual_sugar_individual = gr.Number(label="Residual Sugar", value=mean_values[3])
            chlorides_individual = gr.Number(label="Chlorides", value=mean_values[4])
            free_sulfur_dioxide_individual = gr.Number(label="Free Sulfur Dioxide", value=mean_values[5])
            total_sulfur_dioxide_individual = gr.Number(label="Total Sulfur Dioxide", value=mean_values[6])
            density_individual = gr.Number(label="Density", value=mean_values[7])
            pH_individual = gr.Number(label="pH", value=mean_values[8])
            sulphates_individual = gr.Number(label="Sulphates", value=mean_values[9])
            alcohol_individual = gr.Number(label="Alcohol", value=mean_values[10])

    output = gr.Textbox(label="Prediction")

    # Connect buttons to functions
    button_array.click(
        fn=predict_wine_quality_array,
        inputs=input_array_textbox,
        outputs=output
    )

    button_individual.click(
        fn=predict_wine_quality_individual,
        inputs=[type_radio_individual, fixed_acidity_individual, volatile_acidity_individual, citric_acid_individual, residual_sugar_individual, chlorides_individual,
                free_sulfur_dioxide_individual, total_sulfur_dioxide_individual, density_individual, pH_individual, sulphates_individual, alcohol_individual],
        outputs=output
    )

    # Correct visibility toggle using .change events
    def show_array_input():
        input_container.visible = True
        individual_inputs.visible = False
        return input_container, individual_inputs

    def show_individual_input():
        input_container.visible = False
        individual_inputs.visible = True
        return input_container, individual_inputs

    button_array.click(
        fn=show_array_input,
        inputs=[],
        outputs=[input_container, individual_inputs]
    )

    button_individual.click(
        fn=show_individual_input,
        inputs=[],
        outputs=[input_container, individual_inputs]
    )

demo.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\gradio\queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site

In [17]:
from sklearn.metrics import mean_squared_error, r2_score
Y_pred = model.predict(X_test)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)


print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.39692307692307693
R-squared: 0.47317330619092046


In [ ]:
cm = confusion_matrix(Y_test, Y_pred)
print("Confusion Matrix:\n", cm)

y_discretized = pd.cut(Y, bins=[0, 5, 7, 10], labels=['Low', 'Medium', 'High'])

print(classification_report(Y_test,Y_pred))


Confusion Matrix:
 [[  0   1   1   1   0   0   0]
 [  0   9  33   8   0   0   0]
 [  0   1 315 110   2   0   0]
 [  0   1  83 459  24   0   0]
 [  0   0   2  89 123   0   0]
 [  0   0   2  12  10  13   0]
 [  0   0   0   1   0   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.75      0.18      0.29        50
           5       0.72      0.74      0.73       428
           6       0.68      0.81      0.74       567
           7       0.77      0.57      0.66       214
           8       1.00      0.35      0.52        37
           9       0.00      0.00      0.00         1

    accuracy                           0.71      1300
   macro avg       0.56      0.38      0.42      1300
weighted avg       0.72      0.71      0.70      1300



c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
